usr/lib/libQt5WaylandClient.so.*
usr/lib/qt5/plugins/wayland-graphics-integration-client/libxcomposite-egl.so
usr/lib/qt5/plugins/wayland-graphics-integration-client/libwayland-egl.so
usr/lib/qt5/plugins/wayland-graphics-integration-client/libdrm-egl-server.so
usr/lib/qt5/plugins/wayland-decoration-client/libbradient.so
usr/lib/qt5/plugins/platforms/libqwayland-egl.so
usr/lib/qt5/plugins/platforms/libqwayland-generic.so
usr/lib/qt5/plugins/platforms/libqwayland-xcomposite-egl.so
